### ISSUE TITLE
Add commas to gai generated values 

### ISSUE THREAD

**Issue by philfog** [guldcoin/guld-ai-telegram#15]
For example 

gai, [29.03.18 15:05]
[In reply to Isysd]
$34227609  mizim:Assets
              $-1500    Receivable
--------------------
           $34227609

should be 

gai, [29.03.18 15:05]
[In reply to Isysd]
$34,227,609  mizim:Assets
              $-1,500    Receivable
--------------------
           $34,227,609

**Comment by isysd** [comment]
Fixed by adding commodity definitions with format to price db files.
