### ISSUE TITLE
/send <sender> <recipient> <amount> accepts txs on non-existent usernames

### ISSUE THREAD

**Issue by adriaanbd** [guldcoin/guld-ai-telegram#6]
This issue relates to `sender` parameter from function `def gen_transfer(sender, receiver, amount, commodity="GULD", dt=None, tstamp=None):` in `guldcoin/python-guldlib` ([here](https://github.com/guldcoin/python-guldlib/blob/74ecddf4d5b655ace2c62ab53f5a4ed7b319f39e/guldlib.py#L151-L159)) not checking for existence of username in host's `BLOCKTREE` directory; hence it passes the tx anyway.

Since `guldcoin/guld-ai-telegram` is integrated with `guldcoin/guldlib`, I thought it was appropriate to post it here as well, although I'll create a new issue on `guldcoin/guldlib` as well.

Not sure if this is intentional or not, but non-existent usernames should not be allowed to send transactions. 

For example, the following command goes through:

![image](https://user-images.githubusercontent.com/22228397/37540703-f670b1ae-2925-11e8-92ce-11a57bfb43b0.png)

What I would've expected was for the bot to deny the transaction and indicate that username does not exist.

Any thoughts?

**Comment by isysd** [comment]
This is by design, for now. Many people who contributed indirectly or in the past were airdropped in this fashion last year, and even current contributors may not be registered.
